title: Chase Kusterer
logo:  /assets/images/chase_tedx.jpeg
#description: [text under image]
#show_downloads: True
theme: jekyll-theme-minimal
defaults:
  - 
    scope:
      path: ""
    values:
      layout: default
      css: /assets/css/style.css
