# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hi, I'm Chase
email: chase.kusterer24@gmail.com
description: >- # this means to ignore newlines until "baseurl:" (It will appear in your document head meta (for Google search results) and in your feed.xml site description.)
  Chase Kusterer data scientist and educator project portfolio. Machine learning, AI, higher education.
github_username: chase-kusterer
minimal_mistakes_skin: "dark"
search: true
url: "https://chase-kusterer.github.io"   # canonical url for SEO
baseurl: ""                               # empty for a personal github.io site

# Analytics
analytics:
  provider: "google-gtag" # GA4
  google:
    tracking_id: "G-4M9T92SQR3"
    anonymize_ip: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show (removed since this is a blog feature)
# paginate_path: /page:num/ # amount of posts to show (removed since this is a blog feature)
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# removing Feed button from footer.
atom_feed:
  hide: true

# adding top-level projects block
collections:
  projects:
    output: true
    permalink: /projects/:name/

    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
# - jekyll-paginate (removed since this is a blog feature)
# - jekyll-feed (removed since this is a blog feature)
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag # adding seo tagging

author:
  name   : "Chase Kusterer"
  avatar : "/assets/images/chase-casual-no-bkrd-tight.png"
  bio    : "**Data Scientist | Educator | Author** \n Passionate about creating analytical value with machine learning and AI."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chase-kusterer"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kusterer/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chase-kusterer"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kusterer/"

defaults:
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      classes: wide

  # removing posts since not planning to blog
  # # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: false
  #     share: false
  #     related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# removed below since these are for taxomony pages
# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
